language: swift
osx_image: xcode9.3
podfile: MarkPredictor/Podfile
before_install:
 - gem update cocoapods 
 - pod repo update
 - pod install
script:
  - xcodebuild clean test -scheme MarkPredictor -workspace MarkPredictor.xcworkspace -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=11.3' build test -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'MarkPredictor'
